# Generated by Django 3.1.5 on 2021-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_auto_20210118_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('transports', models.ManyToManyField(blank=True, related_name='passengers', to='transports.Transport')),
            ],
        ),
    ]
